# Generated by Django 6.1 on 2026-09-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_is_settled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Customer'), ('model', 'AI')], max_length=10, verbose_name='sender')),
                ('text', models.TextField(verbose_name='text of message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.customer')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
