# Generated by Django 6.1 on 2026-09-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_conversation', '0001_initial'),
        ('orders', '0006_customer_is_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='customer',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Customer'), ('model', 'AI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing')], default='idle', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Summary of past conversations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='orders.customer')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='model_conversation.conversation'),
            preserve_default=False,
        ),
    ]
