# Generated by Django 6.1 on 2026-09-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_conversation', '0002_remove_chatmessage_customer_alter_chatmessage_sender_and_more'),
        ('orders', '0006_customer_is_buyer'),
        ('stores', '0003_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp', 'id']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_processed_user_message_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('store', 'customer'), name='unique_conversation_per_store_customer'),
        ),
    ]
