# Generated by Django 6.1 on 2026-09-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_conversation', '0003_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('USER', 'Customer'), ('MODEL', 'AI')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('Processing', 'Processing')], default='IDLE', max_length=20),
        ),
    ]
