# Generated by Django 6.1 on 2026-08-31 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0002_store_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store (tenant) this user belongs to. Null only for superusers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='stores.store'),
        ),
    ]
