# Generated by Django 6.1 on 2026-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Store Owner'), ('SHIPPER', 'Shipper'), ('MANAGER', 'Manager')], help_text='Role of the user within the store.', max_length=20, verbose_name='role'),
        ),
    ]
