# Generated by Django 6.1 on 2026-08-30 23:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the store (tenant).', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique name of the store.', max_length=200, unique=True, verbose_name='store name')),
                ('whatsapp_number', models.CharField(db_index=True, help_text="Store's WhatsApp number in international format.", max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +14155552671).', regex='^\\+[1-9]\\d{1,14}$')], verbose_name='WhatsApp number')),
                ('meta_api_token', models.CharField(blank=True, help_text='Token for Meta API integrations. Generated later.', max_length=255, null=True, unique=True, verbose_name='Meta API token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'whatsapp_number'], name='stores_stor_name_3857c6_idx')],
            },
        ),
    ]
