# Generated by Django 6.1 on 2026-08-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this store is active. Unselect this instead of deleting.'),
        ),
    ]
