# Generated by Django 6.1 on 2026-09-01 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='whatsapp_number',
            field=models.CharField(db_index=True, help_text="Store's WhatsApp number in international format.", max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +14155552671).', regex='^\\+[1-9]\\d{8,14}$')], verbose_name='WhatsApp number'),
        ),
    ]
