# Generated by Django 6.1 on 2026-09-14 00:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_remove_category_unique_category_name_per_store_and_more'),
        ('stores', '0003_alter_store_whatsapp_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('phone_number', models.CharField(db_index=True, help_text="Customer's contact phone number (unique per store).", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +14155552671).', regex='^\\+[1-9]\\d{8,14}$')], verbose_name='phone number')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('source', models.CharField(choices=[('DASHBOARD', 'Dashboard (Manual Entry)'), ('WHATSAPP_AI', 'WhatsApp AI Bot')], default='DASHBOARD', help_text='Where the order originated from.', max_length=20, verbose_name='source')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total amount')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer')),
                ('shipper', models.ForeignKey(blank=True, help_text='Shipper assigned to deliver this order (role must be SHIPPER).', limit_choices_to={'role': 'SHIPPER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Snapshot of the product price at the time of purchase.', max_digits=10, verbose_name='price at order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', 'phone_number'], name='orders_cust_store_i_981ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['store', 'is_deleted'], name='orders_cust_store_i_ebd0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'source'], name='orders_orde_store_i_c861c3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'is_deleted'], name='orders_orde_store_i_b8075a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['store', 'is_deleted'], name='orders_orde_store_i_6e6881_idx'),
        ),
    ]
