# Generated by Django 6.1 on 2026-09-14 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, help_text="Customer's contact phone number (unique per store).", max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format (e.g., +14155552671).', regex='^\\+[1-9]\\d{8,14}$')], verbose_name='phone number'),
        ),
    ]
