# Generated by Django 6.1 on 2026-09-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_settled',
            field=models.BooleanField(default=False, verbose_name='The cash has been deposited.'),
        ),
    ]
