# Generated by Django 6.1 on 2026-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='if Customer is buy at lest one order(buyer => at lest order Delivered)'),
        ),
    ]
