# Generated by Django 6.1 on 2026-09-02 23:30

import django.core.validators
import django.db.models.deletion
import products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0003_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the category.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name.', max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', help_text='Optional description.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Visibility flag for customers.', verbose_name='active')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order.', verbose_name='sort order')),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the product.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product name.', max_length=200, verbose_name='name')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit / Barcode (optional, unique per store).', max_length=50, null=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, default='', help_text='Optional product description.', verbose_name='description')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost price (optional).', max_digits=10, null=True, verbose_name='cost price')),
                ('price', models.DecimalField(decimal_places=2, help_text='Regular selling price (must be > 0).', max_digits=10, verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price (optional, must be < price).', max_digits=10, null=True, verbose_name='discount price')),
                ('is_active', models.BooleanField(default=True, help_text='Visibility flag for customers.', verbose_name='active')),
                ('is_out_of_stock', models.BooleanField(default=False, help_text="If True, show 'Out of Stock' in UI.", verbose_name='out of stock')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order within category.', verbose_name='sort order')),
                ('category', models.ForeignKey(help_text='Category this product belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='whether this %(class) is deleted. Unselect this instead of deleting.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the image.', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Product image file (max 2MB, formats: JPG, JPEG, PNG, WEBP).', upload_to=products.models.product_image_upload_path, validators=[products.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='image')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the main catalog image.', verbose_name='primary')),
                ('sort_order', models.IntegerField(default=0, help_text='Display order among images.', verbose_name='sort order')),
                ('product', models.ForeignKey(help_text='Product this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
                ('store', models.ForeignKey(help_text='The store (tenant) this record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_related', to='stores.store')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store', 'sort_order'], name='products_ca_store_i_79bc59_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['store', 'name'], name='products_ca_store_i_dcc65a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'category'], name='products_pr_store_i_601a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='products_pr_store_i_719494_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'sort_order'], name='products_pr_store_i_ed49db_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', None), _negated=True), fields=('store', 'sku'), name='unique_sku_per_store'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
    ]
