# Generated by Django 6.1 on 2026-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_unique_category_name_per_store'),
        ('stores', '0003_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'category', 'name'), name='unique_product_name_per_category_in_store'),
        ),
    ]
