# Generated by Django 6.1 on 2026-09-03 00:00

import django.core.validators
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_unique_product_name_per_category_in_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Product image file (max 2MB, formats: JPG, JPEG, PNG, WEBP).', max_length=255, upload_to=products.models.product_image_upload_path, validators=[products.models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='image'),
        ),
    ]
