# Generated by Django 6.1 on 2026-09-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image'),
        ('stores', '0003_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['stock_quantity', 'name'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_store_i_ed49db_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of items currently available in stock.', verbose_name='stock quantity'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'stock_quantity'], name='products_pr_store_i_52da78_idx'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sort_order',
        ),
    ]
