# Generated by Django 6.1 on 2026-09-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options_and_more'),
        ('stores', '0003_alter_store_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_per_store',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('store', 'name'), name='unique_active_category_name_per_store'),
        ),
    ]
