# Generated by Django 6.1 on 2026-09-14 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_category_unique_category_name_per_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_out_of_stock',
        ),
    ]
