# Generated by Django 6.1 on 2026-09-21 09:11

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text representation used to generate the embedding.')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('model_name', models.CharField(default='gemini-embedding-2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='products.product')),
            ],
        ),
    ]
